//
// AccountAllOfAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountAllOfAttributes: Codable, JSONEncodable, Hashable {

    public var id: String
    public var firstName: String
    public var secondName: String
    public var name: String
    public var email: String
    /** optional */
    public var photo: String

    public init(id: String, firstName: String, secondName: String, name: String, email: String, photo: String) {
        self.id = id
        self.firstName = firstName
        self.secondName = secondName
        self.name = name
        self.email = email
        self.photo = photo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case firstName
        case secondName
        case name
        case email
        case photo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(secondName, forKey: .secondName)
        try container.encode(name, forKey: .name)
        try container.encode(email, forKey: .email)
        try container.encode(photo, forKey: .photo)
    }
}

