//
// AccountLocationAllOfRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountLocationAllOfRelationships: Codable, JSONEncodable, Hashable {

    public var accountId: String

    public init(accountId: String) {
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
    }
}

