//
// BasicRatingAllOfAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BasicRatingAllOfAttributes: Codable, JSONEncodable, Hashable {

    public var rating: Double

    public init(rating: Double) {
        self.rating = rating
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rating
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rating, forKey: .rating)
    }
}

