//
// CreateAccountRequestAllOfAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAccountRequestAllOfAttributes: Codable, JSONEncodable, Hashable {

    public var name: String
    public var secondName: String
    public var email: String
    public var password: String
    /** optional */
    public var photo: String

    public init(name: String, secondName: String, email: String, password: String, photo: String) {
        self.name = name
        self.secondName = secondName
        self.email = email
        self.password = password
        self.photo = photo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case secondName
        case email
        case password
        case photo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(secondName, forKey: .secondName)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encode(photo, forKey: .photo)
    }
}

