//
// CreateSwapOfferProposalAllOfRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateSwapOfferProposalAllOfRelationships: Codable, JSONEncodable, Hashable {

    public var swapOfferId: String

    public init(swapOfferId: String) {
        self.swapOfferId = swapOfferId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case swapOfferId = "swap_offer_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(swapOfferId, forKey: .swapOfferId)
    }
}

