//
// ErrorsErrorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorsErrorsInner: Codable, JSONEncodable, Hashable {

    public enum Status: Int, Codable, CaseIterable {
        case _400 = 400
        case _401 = 401
        case _403 = 403
        case _404 = 404
        case _409 = 409
        case _500 = 500
    }
    /** Short, human-readable summary of the problem */
    public var title: String
    /** Human-readable explanation specific to this occurrence of the problem */
    public var detail: String?
    /** HTTP status code applicable to this problem */
    public var status: Status

    public init(title: String, detail: String? = nil, status: Status) {
        self.title = title
        self.detail = detail
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case detail
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encode(status, forKey: .status)
    }
}

