//
// GetSwapProposalsByOfferId200ResponseIncludedInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetSwapProposalsByOfferId200ResponseIncludedInner: Codable, JSONEncodable, Hashable {
    case typeAccount(Account)
    case typeBrand(Brand)
    case typeWatch(Watch)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAccount(let value):
            try container.encode(value)
        case .typeBrand(let value):
            try container.encode(value)
        case .typeWatch(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(Account.self) {
            self = .typeAccount(value)
        } else if let value = try? container.decode(Brand.self) {
            self = .typeBrand(value)
        } else if let value = try? container.decode(Watch.self) {
            self = .typeWatch(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetSwapProposalsByOfferId200ResponseIncludedInner"))
        }
    }
}

