//
// RateAllOfAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RateAllOfAttributes: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case swapOfferRating = "swap-offer-rating"
    }
    public var rating: Int
    public var timestamp: Int64
    public var kind: Kind

    public init(rating: Int, timestamp: Int64, kind: Kind) {
        self.rating = rating
        self.timestamp = timestamp
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rating
        case timestamp
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rating, forKey: .rating)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(kind, forKey: .kind)
    }
}

