//
// RateAllOfRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RateAllOfRelationships: Codable, JSONEncodable, Hashable {

    public var accountId: String
    public var instanceId: String

    public init(accountId: String, instanceId: String) {
        self.accountId = accountId
        self.instanceId = instanceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case instanceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(instanceId, forKey: .instanceId)
    }
}

