//
// SetOfferProposalStatusAllOfRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetOfferProposalStatusAllOfRelationships: Codable, JSONEncodable, Hashable {

    public var swapOfferProposalId: String

    public init(swapOfferProposalId: String) {
        self.swapOfferProposalId = swapOfferProposalId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case swapOfferProposalId = "swap-offer-proposal-id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(swapOfferProposalId, forKey: .swapOfferProposalId)
    }
}

