//
// SignInResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignInResponse: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case signInResponse = "sign-in-response"
    }
    public var type: ModelType
    public var attributes: SignInResponseAllOfAttributes

    public init(type: ModelType, attributes: SignInResponseAllOfAttributes) {
        self.type = type
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(attributes, forKey: .attributes)
    }
}

