//
// SwapProposalOffer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SwapProposalOffer: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case swapOfferProposalOffer = "swap-offer-proposal-offer"
    }
    public var type: ModelType
    public var id: String
    public var relationships: SwapProposalOfferAllOfRelationships
    public var attributes: SwapProposalOfferAllOfAttributes

    public init(type: ModelType, id: String, relationships: SwapProposalOfferAllOfRelationships, attributes: SwapProposalOfferAllOfAttributes) {
        self.type = type
        self.id = id
        self.relationships = relationships
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case relationships
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(id, forKey: .id)
        try container.encode(relationships, forKey: .relationships)
        try container.encode(attributes, forKey: .attributes)
    }
}

