//
// SwapProposalOfferAllOfRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SwapProposalOfferAllOfRelationships: Codable, JSONEncodable, Hashable {

    public var proposalInitiatorId: String
    public var proposalApproverId: String
    public var initiatorId: String
    public var sellerId: String

    public init(proposalInitiatorId: String, proposalApproverId: String, initiatorId: String, sellerId: String) {
        self.proposalInitiatorId = proposalInitiatorId
        self.proposalApproverId = proposalApproverId
        self.initiatorId = initiatorId
        self.sellerId = sellerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case proposalInitiatorId = "proposal_initiator_id"
        case proposalApproverId = "proposal_approver_id"
        case initiatorId = "initiator_id"
        case sellerId = "seller_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(proposalInitiatorId, forKey: .proposalInitiatorId)
        try container.encode(proposalApproverId, forKey: .proposalApproverId)
        try container.encode(initiatorId, forKey: .initiatorId)
        try container.encode(sellerId, forKey: .sellerId)
    }
}

