//
// SwapOfferAllOfRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SwapOfferAllOfRelationships: Codable, JSONEncodable, Hashable {

    public var initiatorId: String
    public var sellerId: String
    public var swapWatchId: String
    public var offeredWatchId: String

    public init(initiatorId: String, sellerId: String, swapWatchId: String, offeredWatchId: String) {
        self.initiatorId = initiatorId
        self.sellerId = sellerId
        self.swapWatchId = swapWatchId
        self.offeredWatchId = offeredWatchId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case initiatorId = "initiator_id"
        case sellerId = "seller_id"
        case swapWatchId = "swap_watch_id"
        case offeredWatchId = "offered_watch_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(initiatorId, forKey: .initiatorId)
        try container.encode(sellerId, forKey: .sellerId)
        try container.encode(swapWatchId, forKey: .swapWatchId)
        try container.encode(offeredWatchId, forKey: .offeredWatchId)
    }
}

