//
// SyncAccountWatchesRequestAllOfAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncAccountWatchesRequestAllOfAttributes: Codable, JSONEncodable, Hashable {

    public var watches: [SyncAccountWatchItem]

    public init(watches: [SyncAccountWatchItem]) {
        self.watches = watches
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case watches
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(watches, forKey: .watches)
    }
}

