//
// SyncAccountSwapOffersAllOfAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncAccountSwapOffersAllOfAttributes: Codable, JSONEncodable, Hashable {

    public var toUpdate: [SwapOffer]
    public var toRemove: [String]

    public init(toUpdate: [SwapOffer], toRemove: [String]) {
        self.toUpdate = toUpdate
        self.toRemove = toRemove
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case toUpdate
        case toRemove
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(toUpdate, forKey: .toUpdate)
        try container.encode(toRemove, forKey: .toRemove)
    }
}

