//
// SyncAccountWatchItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncAccountWatchItem: Codable, JSONEncodable, Hashable {

    public var watchId: String
    public var timestamp: Int64

    public init(watchId: String, timestamp: Int64) {
        self.watchId = watchId
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case watchId = "watch-id"
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(watchId, forKey: .watchId)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

