//
// WatchAllOfRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WatchAllOfRelationships: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    public var brandId: String?

    public init(accountId: String? = nil, brandId: String? = nil) {
        self.accountId = accountId
        self.brandId = brandId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case brandId = "brand_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(brandId, forKey: .brandId)
    }
}

