//
// Watch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Watch: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case watch = "watch"
    }
    public var type: ModelType
    public var id: String
    public var relationships: WatchAllOfRelationships?
    public var attributes: WatchAllOfAttributes

    public init(type: ModelType, id: String, relationships: WatchAllOfRelationships? = nil, attributes: WatchAllOfAttributes) {
        self.type = type
        self.id = id
        self.relationships = relationships
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case relationships
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(relationships, forKey: .relationships)
        try container.encode(attributes, forKey: .attributes)
    }
}

