//
// VoucherAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class VoucherAPI {

    /**

     - parameter accessToken: (header)  
     - parameter pageSize: (query)  (optional, default to 15)
     - parameter pageNumber: (query) The number of a page to return. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getUserVouchers(accessToken: String, pageSize: Int? = nil, pageNumber: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: GetUserVouchers200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getUserVouchersWithRequestBuilder(accessToken: accessToken, pageSize: pageSize, pageNumber: pageNumber).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /integrations/watch-svc-go/vauchers/user
     - returns user vouchers
     - parameter accessToken: (header)  
     - parameter pageSize: (query)  (optional, default to 15)
     - parameter pageNumber: (query) The number of a page to return. (optional)
     - returns: RequestBuilder<GetUserVouchers200Response> 
     */
    open class func getUserVouchersWithRequestBuilder(accessToken: String, pageSize: Int? = nil, pageNumber: Int? = nil) -> RequestBuilder<GetUserVouchers200Response> {
        let localVariablePath = "/integrations/watch-svc-go/vauchers/user"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page[size]": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "page[number]": (wrappedValue: pageNumber?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "access-token": accessToken.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetUserVouchers200Response>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
